### ISSUE TITLE
Add rabbitmq/support-tools

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server-boshrelease#29]
https://github.com/rabbitmq/support-tools

Consume `rabbitmq-collect-env` from here

**Comment by gerhard** [comment]
@lukebakken would you mind adding the queue masters rebalancing script to rabbitmq/support-tools?

**Comment by lukebakken** [comment]
Done!

https://github.com/rabbitmq/support-tools/blob/master/scripts/rebalance-queue-masters
